theme = "hugo-xmin"
baseURL = "https://notes.rmhogervorst.nl/"
languageCode = "en-us"
title = "A braindump of unfinished ideas that are just not there yet"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "index\\.html", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = false
footnotereturnlinkcontents = "↩"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
    footnote = true

    [markup.goldmark.renderer]
    unsafe = false

[permalinks]
post = "/post/:year/:month/:day/:slug/"
note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Notes main page"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Main blog: Roel's R-tefacts"
    url = "https://blog.rmhogervorst.nl"
    weight = "2"
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Post type"
    url = "/post-type/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
[[menu.main]]
    name = "Search"
    url = "/search/"
[[menu.main]]
    name = "mastodon"
    url = "https://mastodon.world/@rmhogervorst"
[[menu.main]]
    name="my personal (public) inspiration + visualisation feed on pinboard"
    url="https://pinboard.in/u:rmhogervorst/t:inspiration/t:visualisation/"


[params]
description = "A website built through Hugo and blogdown, deployed through netlify"
#footer = "&copy; [Yihui Xie](https://yihui.name) 2017 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"

[outputs]
   home = [ "HTML", "JSON" ]

[taxonomies]
   category = 'categories'
   tag = 'tags'
   post-type = 'post-type'
   difficulty = 'difficulty'
