theme = "hugo-xmin"
baseURL = "https://notes.rmhogervorst.nl/"
languageCode = "en-us"
title = "A braindump of unfinished ideas that are just not there yet"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html"]
preserveTaxonomyNames = false
footnotereturnlinkcontents = "↩"

[permalinks]
post = "/post/:year/:month/:day/:slug/"
note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Notes main page"
    url = "/post/"
    weight = 1
[[menu.main]]
    name = "Main blog: Roel's R-tefacts"
    url = "https://blog.rmhogervorst.nl"
    weight = "2"
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
[[menu.main]]
    name = "twitter"
    url = "https://twitter.com/roelmhogervorst"
[[menu.main]]
    name="my personal inspiration + visualisation feed on pinboard"
    url="https://pinboard.in/u:rmhogervorst/t:inspiration/t:visualisation/"


[params]
description = "A website built through Hugo and blogdown."
#footer = "&copy; [Yihui Xie](https://yihui.name) 2017 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"
