# Global settings applied to the whole site.
[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.82.0"

